{% set name = "PyHive" %}
{% set version = "0.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00fe5b9a4289b5d40d3ccb7bad52a76982f485c7350a792a80d31277d26a7fd1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - future
    - python >=3.6
    - python-dateutil
    - thrift >=0.10.0
    - thrift_sasl >0.2.1
    - requests >=1.0.0
    - sqlalchemy >=0.8.7

test:
  imports:
    - TCLIService
    - pyhive
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/PyHive/
  summary: Python interface to Hive
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    PyHive is a collection of Python DB-API and SQLAlchemy interfaces for Presto and Hive.
  doc_url: https://pypi.python.org/pypi/PyHive
  doc_source_url: https://github.com/dropbox/PyHive/blob/master/README.rst

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bandersen23
